server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/knitting_platform?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


cors.allowed-origins=http://localhost:3000,http://localhost:8081

# 이미지 업로드
app.upload.dir=uploads
app.base-url=http://10.252.60.21:8080
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB
