server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/knitting_platform?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


cors.allowed-origins=http://localhost:3000,http://localhost:8081

# 이미지 업로드
app.upload.dir=uploads
server.base-url=http://192.168.200.161:8080

# Discord Webhook
discord.webhook.url=https://discord.com/api/webhooks/1515727630455013396/x5DlCZqgh3gldZ3xh8Bf3-YC4D-kAXAmJl4JFAqINpDcqb2eSn1VFMeTSf6KRe5XXV_x

# JWT
app.jwt.secret=LoopLearnSecretKey2026MustBe256BitsOrLongerForHmacSha256Algorithm
app.jwt.access-token-expiry=3600000
app.jwt.refresh-token-expiry=1209600000
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB
